sudo: required
dist: trusty
services:
- docker
git:
  submodules: false
branches:
  only:
  - master
env:
  global:
  - secure: B1eKgCvwBn3XEsvPuyPDCRA21tsKcWT23XVP+/8S1ylqHjQr1EBa4NhiXvkeGOtWkSLLtyiXKGt6uC4V7aXvw/HE6JEjuNTizx7ATwyX1FsZh6M5aASa18jklP4ZcQlb0RFs7yOLmggpIP+O2kH1fFx+yfL3a6cav/43gFqNb6iNBNrZAi3ISMmxacyub9EswRoqp04Lm2mGHSgOs3fnTuFpFmzUsf56mDMgrGNHdfeTpIH5MtAl3cbmpvLHoz6SGGSg9V12v3G6fLi5U67ULKB7YT3hwBv+jyXO5ziDwT03KmRu7kKrkFWX7kpIoPvsRoKef4/xnzI+WuuBgzdJ/UVVBkhCxX0Q9n1SLlUh3rXg7WtSDqC9rnY6ueBeA7I2U9Xf2tegbpDYXMogbjBll9TPgQNyTp9h8EJQYytpDihjrH1otqg8ZJGH48M6YCdydLoCtFZdFTZ5OG6xmmfqhdPVTeUeabK4yTKvASuYK3p/0eH3MYlb3Ve3/F1m/TVbWgvboGJwLQ9tgHDus8vg22WKg8z7Riu7yTDMqagp87GgsjwQ10rj8pfxqHdGbz9iDI0+Y5UoxYkt1a6kPehIpcX0W8FT560PIgMK00ZeuCKoyTcluHFZhPgwRUodMJlZO7NK151v6SLJv78B/HQupq67aw7+BJ1cWm56K5k7yyo=
  - secure: shhn4iC6tU0L953x++KElQvtDCWEwueyeKrPHA29bGiCNRuvBf4o6x3sS8xWPvg5dHm7vabax/eH2qUazB4l1TuYG9DwL/s5lq5N8dyMjhUvRtjb2ieAYPKeFvmzcRaUnYwd3IHDKZTiB8dSk3pM6ntMhY+wmtxym8DSC31a71R/T5fiP6fPNHtiTsrEXRVvXXbFLYLREw/hu0m++o/ftp3XiFgLFuRH7zaKNy9oyEvJ4xF4s9+M1tPIMWfRb7JbOyb2GL7JNGEbA3rada000uNr395o3VwbrgJN8Sa2mFe7zplpQ99qJQI6/GpuZxi65i/PbHL1bp7UUwq0FfwWrzbRBtvs9dzY5I9SM1kHYR5GXUxCBHOGJ0DIHwNq2Z6y21FvrSr4aI31hpSlKSWo82yR+9CG5mBd5HtGNbi8Ye0KBVE5xDL6TaKDk/Kgh7vXqCZUmZLYWlBc/o0B/9ECxTPXC2ANYRV78q3ROl+g8jCO0033OJdN6sXoflO6wWA29ShFjK+e88nArrcmQwpEer3myqNQccQ9oggB+7nEcLKJIcrKTPZo6MYAwEvti0771f+WnanNPSNAZyIHXeMsooQjAcxRwA9zwX5EgYkJwOWv/aFDmAd4Y25LPB3FagpIRd5aTkCuJcQf3xGUGsFHedlWA/ZlJZftkRfqKmwVERs=
  - secure: gIqfH0+mTRc4h8HIwdSefCxpxOtKYZLslqohuzzF+aO70aH2by+mv+CSOi78+Sugv1YTi8e4gzRG9G9sD1LTNlZbTq0HdJqSqXMYLpXh4qmGzm0Kv0vvONo7ZHbzgZUYGK0kNBBpgJGa1cqFHsQmn/rxZ8oxa+6GgtebGi+Mz/+/UeeW2J0S+NFCZwo/AK8u8YfCpaQLujW9VPWvG+kyfsJTGelQM8Ep2CAaHO/15KKLFT33ZoKu0yhDAVejW+7z8r+gk2VqJQx79WQnNKvHkupUkNWzu6arRQWOiDXIW6N8UzxgUuEmTGJCvjehQpng6qqOUZGNMtJ1okm9sHOK+1iw3OS2UzRK5vAbW1KF1vjMifzYyQoYbmYjtCkm+AbCSPbZhDL4MZNIMWPpRvGMxXAiU+THHoa1Vw1EWth/bDlIHdruemEY9GJy5JDu+MK5BsZ4LgFnyv9fmaSWJYyiXhB02GG1gnWU/yHBJC9u3MQmWt2UFRG0xEgj9pIH18ePiosF4/K26ZetZ1qFNImhw5SJDUjiokdHvFMlEpjmnFA4GdPRY01IKqOoOR6LdIWw+TGTo5HCjWJCpfzN8+6Mok2DWjO7XRoBODsTTcTDg6713G8q7KwNQ9WJy3vHFVIaA4yNckeX/CxI83IXxcA8j5bSY3WMLjCr9p9osyFIwyE=
  matrix:
  - cw_DIST=el7 cw_VERSION=1.6 ci_UPLOAD=false
  - cw_DIST=el7 cw_VERSION=1.7 ci_UPLOAD=false
  - cw_DIST=el7 cw_VERSION=1.8 ci_UPLOAD=false
  - cw_DIST=el7 cw_VERSION=1.9 ci_UPLOAD=true
before_install:
- git clone https://github.com/alces-software/gridware-ci.git .gridware-ci
- curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install |
  bash
- ".gridware-ci/build-container.sh"
script:
- travis_wait 50 .gridware-ci/build-packages.sh
- ".gridware-ci/upload-artifacts.sh"
after_failure:
- ".gridware-ci/dump-logs.sh"
- echo "Build failed :'("
notifications:
  slack:
    secure: e2XI42Slv8KRMhvOjg98MBRq6rSEncA3G1t6R5d2T75Ce3gPcbwxy8oJFSmLg0kk9orUIu8+NjeWCsoYM2YWUehClG5vsbZ60UP2TdesgeRwGLKP7e9Zqc3CsjpDhiwOP0XzAqCUnZG0Z7pRmhiUm8rDGu4Cv9RJmeGr371UTkMiyeEOzW0vT8LIp17ZKo9+huyGPs0e8Q3Wh12NYkBFrGYq8WGMwOyI3T+MVXcSDEnddberAUO/JTw7jPVN4FAL9kmbscUNIhdrQ2GPaDvwW/ULC672vdQPECVKMSGyF4J4XBachx15B/vFoiK1lJiFzaOd55628ESN6K1JRLb6eqYchs8d3YKBSPN4YjhsTjbJDyQm4gCycjCPGVjn1QcyxEaSwrQvAa2EmN1ge+sAIPtiHxytOBdHOTDQaMijxXvOYBxHXsKy6yLILp+VDht2P+PCGP/BiOsxNBj36Q8B8+EKzBZEx8uLVGVz1Wzf7KONtGWZLIjszcPp6OQOsASU7T7E3xrsuFNbOUVXtI/orO2SAbh5yltBq8rx/SMd7kZ0J8IINlflgDYTe+vsA67pxKc4Pgww1OGtyhtLNVYqvK3ctfjD3pTbdbKzxYD5EmQ6lvwI4CqbxMA11XMDGSXlUUATUQcX+baKEiovnfse6anoXgAG6MZHkVKXzoj8Yso=
