--- SuiteSparse_config/SuiteSparse_config.mk.orig       2022-04-10 21:44:14.000000000 +0100
+++ SuiteSparse_config/SuiteSparse_config.mk    2022-08-11 08:42:23.604497821 +0100
@@ -154,7 +154,7 @@

     # The CF macro is used by SuiteSparse Makefiles as a combination of
     # CFLAGS, CPPFLAGS, TARGET_ARCH, and system-dependent settings.
-    CF ?= $(CFLAGS) $(CPPFLAGS) $(TARGET_ARCH) $(OPTIMIZATION) -fexceptions -fPIC
+    CF ?= $(CFLAGS) $(CPPFLAGS) $(CPPFLAGS2) $(TARGET_ARCH) $(OPTIMIZATION) -fexceptions -fPIC

     #---------------------------------------------------------------------------
     # code formatting (for Tcov on Linux only)
@@ -170,7 +170,7 @@
     # It places its shared *.so libraries in SuiteSparse/lib.
     # Linux also requires the -lrt library (see below)
     LDLIBS ?= -lm
-    LDFLAGS += -L$(INSTALL_LIB)
+    LDFLAGS += -L$(INSTALL_LIB) $(LDFLAGS2)

     # NOTE: Use of the Intel MKL BLAS is strongly recommended.  The OpenBLAS can
     # result in severe performance degradation, in CHOLMOD in particular.
