--- src/Makefile.orig	2015-08-24 17:01:57.839448694 +0000
+++ src/Makefile	2015-08-24 17:02:08.967449213 +0000
@@ -181,7 +181,7 @@
 top_build_prefix = ../
 top_builddir = ..
 top_srcdir = ..
-AM_CXXFLAGS = -lrt -I'seqan/core/include/' -Wall -Wno-long-long -pedantic -Wno-variadic-macros -fopenmp -static 
+AM_CXXFLAGS = -lrt -I'seqan/core/include/' -Wall -Wno-long-long -pedantic -Wno-variadic-macros -fopenmp 
 __top_builddir__bin_Q_SOURCES = Q_EvaluateSignalsPvalue.cpp  Q_ReadInFiles.cpp Q.cpp Q_EvaluateSignalsPvalue.h \
 Q_ReadInFiles.h Q_DetectSignals.cpp         Q_GetFragLength.cpp          Q_WriteResults.cpp \
 Q_DetectSignals.h Q_GetFragLength.h Q_WriteResults.h Q_EvaluateSignalsCount.cpp  \
