--- Makefile.orig	2017-12-22 15:28:43.000000000 +0000
+++ Makefile	2018-03-14 17:11:19.016439842 +0000
@@ -53,7 +53,7 @@
 
 ## Build Python lib
 iced: $(INST_SOURCES)/ice_mod
-	(cp $(INST_SOURCES)/ice_mod/iced/scripts/ice ${INST_SCRIPTS}; cd $(INST_SOURCES)/ice_mod/; ${PYTHON_PATH}/python setup.py install;)
+	cp $(INST_SOURCES)/ice_mod/iced/scripts/ice ${INST_SCRIPTS}
 
 test: config_check
 	@echo ${PYTHON_PATH}
